select * FROM ALQUILER
SELECT * FROM PELICULA
SELECT * FROM cliente
delete from alquiler

SELECT TITULO_PELICULA, PRECIO_PELICULA, CEDULA_CLIENTE, FECHAALQUILER_PELICULA, FECHADEVOLUCION_PELICULA FROM PELICULA JOIN ALQUILER ON PELICULA.ID_ALQUILER=ALQUILER.ID_ALQUILER where CEDULA_cliente = '1721822623';

SELECT  FROM ALQUILER 

SELECT * FROM PELICULA JOIN ALQUILER ON PELICULA.ID_ALQUILER = ALQUILER.ID_ALQUILER where CEDULA_cliente = '1721822623';

SELECT FECHADEVOLUCION_PELICULA FROM PELICULA JOIN ALQUILER ON PELICULA.ID_ALQUILER = ALQUILER.ID_ALQUILER where CEDULA_cliente = '1721822623' UPDATE ALQUILER SET FECHADEVOLUCION_PELICULA = NULL;


UPDATE PELICULA SET ID_ALQUILER = (SELECT MAX(ID_ALQUILER) FROM ALQUILER) WHERE TITULO_PELICULA = 'Rapidos y Furiosos'

delete from alquiler

SELECT MAX(ID_ALQUILER)+1 FROM ALQUILER

INSERT INTO ALQUILER(ID_ALQUILER, CEDULA_CLIENTE, FECHAALQUILER_PELICULA) VALUES(1,'1721822623',27/01/2017);




